- name: check a number is less than 20 or not
  hosts: local
  connection: local
  vars_prompt:
  - name: my_number
    prompt: Please enter the number
    private: false # not confidential
  # vars:
  #   my_number: 139 # number
  tasks:
  - name: print this if less than 20
    ansible.builtin.debug:
      msg: "Given number {{ my_number }} is less than 10"
    when: my_number | int < 20 # conditional expression

  - name: print this if greater than or equal to 20
    ansible.builtin.debug:
      msg: "Given number {{ my_number }} greater than or equal to 20"
    when: my_number | int >= 20